name: action-poem
author: microsoft
description: This is the title
inputs:
  github_token:
    description: "GitHub token with `models: read` permission at least."
    required: true
outputs:
  text:
    description: The generated text output.
    required: false
  data:
    description: The generated JSON data output, parsed and stringified.
    required: false
branding:
  color: purple
  icon: anchor
runs:
  using: docker
  image: Dockerfile
