name: genaiscript
author: microsoft
description: This is the title
inputs:
  github_token:
    description: "GitHub token with `models: read` permission at least."
    required: true
  debug:
    description: Enable debug logging.
    required: false
outputs:
  text:
    description: The generated text output.
  data:
    description: The generated JSON data output, parsed and stringified.
branding:
  color: purple
  icon: anchor
runs:
  using: docker
  image: Dockerfile
