name: genai tests

on:
    workflow_dispatch:
    schedule:
        - cron: "0 7 * * *"
concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  submodules: "recursive"
                  fetch-depth: 0
            - uses: pnpm/action-setup@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: "22"
                  cache: pnpm
            - run: pnpm install --frozen-lockfile
            - name: compile
              run: pnpm build:cli
            - name: download ollama docker
              run: pnpm ollama:start
            - name: run test within scripts
              run: pnpm test:scripts --out-summary $GITHUB_STEP_SUMMARY --test-delay 10
