name: build
permissions:
    contents: read
    models: read
on:
    push:
        branches: [main, dev]
    pull_request:
    workflow_dispatch:
jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [22, 23, 24]
        steps:
            - uses: actions/checkout@v4
              with:
                  submodules: "recursive"
                  fetch-depth: 10
            - uses: pnpm/action-setup@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: "${{ matrix.node-version }}"
                  cache: 'pnpm'
            - run: sudo apt-get update && sudo apt-get install ffmpeg
            - run: pnpm install --frozen-lockfile
            - name: build
              run: pnpm run build:ci
            - name: lint:check
              run: pnpm run lint:check
              continue-on-error: true
            - name: compile system scripts
              run: pnpm run test:system
            - name: core tests
              run: pnpm run test:core
            - name: compile tests
              run: pnpm run test:compile
              continue-on-error: true
            - name: unit tests
              run: pnpm run test:samples
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - name: unit test:modulesamples
              run: pnpm run test:modulesamples
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
