name: genai issue bot
permissions:
    contents: read
    issues: write
    models: read
on:
    workflow_dispatch:
        inputs:
            issue-number:
                description: "Issue number to process"
                required: true
    issues:
        types: [closed]
concurrency:
    group: issue-bot-${{ github.event.issue.number }}
    cancel-in-progress: true
jobs:
    reason:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  submodules: "recursive"
                  fetch-depth: 10
            - uses: pnpm/action-setup@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: "22"
                  cache: pnpm
            - run: pnpm install --frozen-lockfile
            - name: compile
              run: pnpm compile
            - name: genaiscript issue-review
              run: node packages/cli/dist/src/index.js run issue-bot -p github -prc bot --out-output $GITHUB_STEP_SUMMARY
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  GITHUB_ISSUE: ${{ github.event.issue.number}}
