name: genai commander
on:
    issue_comment:
        types: [created]
jobs:
    pr_commented:
        # must be PR and have a comment starting with /genai
        if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, '/genai-') }}
        runs-on: ubuntu-latest
        permissions:
            contents: write
            pull-requests: write
        steps:
            - name: resolve pr sha
              id: sha
              uses: actions/github-script@v4
              with:
                  result-encoding: string
                  script: |
                      const { owner, repo, number } = context.issue;
                      const pr = await github.pulls.get({ owner, repo, pull_number: number, });
                      return pr.data.head.sha
            - uses: actions/checkout@v4
              with:
                  ref: main
            - uses: actions/checkout@v4
              with:
                  ref: ${{ steps.sha.outputs.result }}
            - uses: actions/setup-node@v4
              with:
                  node-version: "20"
                  cache: yarn
            - run: yarn install --frozen-lockfile
            - name: compile
              run: yarn compile
            - name: genaiscript pr-describe
              if: contains(github.event.comment.body, '/genai-describe')
              run: node packages/cli/built/genaiscript.cjs run pr-describe --out ./temp/genai/pr-describe -prd --out-trace $GITHUB_STEP_SUMMARY
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
                  OPENAI_API_TYPE: ${{ secrets.OPENAI_API_TYPE }}
                  OPENAI_API_BASE: ${{ secrets.OPENAI_API_BASE }}
            - name: genaiscript pr-review
              if: contains(github.event.comment.body, '/genai-review')
              run: node packages/cli/built/genaiscript.cjs run pr-review --out ./temp/genai/pr-review -prc --out-trace $GITHUB_STEP_SUMMARY
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  GITHUB_COMMIT_SHA: ${{ steps.sha.outputs.result }}
                  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
                  OPENAI_API_TYPE: ${{ secrets.OPENAI_API_TYPE }}
                  OPENAI_API_BASE: ${{ secrets.OPENAI_API_BASE }}
            - name: Archive genai results
              if: always()
              uses: actions/upload-artifact@v4
              with:
                  name: genai-results
                  path: ./temp/genai/**
