name: genai issue review
permissions:
    contents: read
    issues: write
    models: read
on:
    issues:
        types: [opened, edited]
concurrency:
    group: issues-${{ github.event.issue.number }}
    cancel-in-progress: true
jobs:
    issue-review:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  submodules: "recursive"
                  fetch-depth: 10
            - uses: pnpm/action-setup@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: "22"
                  cache: pnpm
            - run: pnpm install --frozen-lockfile
            - name: compile
              run: pnpm compile
            - name: genaiscript issue-review
              run: node packages/cli/dist/src/index.js run issue-reviewer -p github --pull-request-comment --out-trace $GITHUB_STEP_SUMMARY
              env:
                  GITHUB_ISSUE: ${{ github.event.issue.number }}
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
