name: genai linters
on:
    workflow_dispatch:
    pull_request:
        types: [opened, ready_for_review, reopened, review_requested]
        paths:
            - "docs/**"
            - "genaisrc/**"
            - "packages/core/**/*"
            - "packages/cli/**/*"
            - "packages/samples/**/*"
            - "packages/vscode/**/*"
concurrency:
    group: linters-${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true
env:
    GENAISCRIPT_MODEL_LINTER: ${{ vars.GENAISCRIPT_MODEL_LINTER }}
jobs:
    lint:
        runs-on: ubuntu-latest
        permissions:
            pull-requests: write
            models: read
        steps:
            - uses: actions/checkout@v4
              with:
                  submodules: "recursive"
                  fetch-depth: 10
            - uses: pnpm/action-setup@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: "22"
                  cache: pnpm
            - run: pnpm install --frozen-lockfile
            - name: compile
              run: pnpm compile
            - name: git stuff
              run: git fetch origin && git pull origin dev:dev
            - name: genaiscript
              run: node packages/cli/dist/src/index.js run linters --out ./temp/genai/linters --pull-request-reviews --pull-request-comment -m linter --out-trace $GITHUB_STEP_SUMMARY --vars defaultBranch=dev
              continue-on-error: true
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  GITHUB_COMMIT_SHA: ${{ github.event.pull_request.base.sha}}
            - name: Archive genai results
              if: always()
              uses: actions/upload-artifact@v4
              with:
                  name: genai-results
                  path: ./temp/genai/**
