name: genai docs
on:
    workflow_dispatch:
    pull_request:
        types: [review_requested]
        paths:
            - "packages/**/*.ts"
concurrency:
    group: docs-${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true
jobs:
    lint:
        runs-on: ubuntu-latest
        permissions:
            pull-requests: write
            content: write
            models: read
        steps:
            - uses: actions/checkout@v4
              with:
                  submodules: "recursive"
                  fetch-depth: 10
            - uses: actions/setup-node@v4
              with:
                  node-version: "20"
                  cache: yarn
            - run: yarn install --frozen-lockfile
            - name: compile
              run: yarn compile
            - name: git stuff
              run: git fetch origin && git pull origin dev:dev
            - name: genaiscript
              run: node packages/cli/built/genaiscript.cjs run docs --out ./temp/genai/docs -p github --out-trace $GITHUB_STEP_SUMMARY --vars pretty=true --vars applyEdits=true --vars defaultBranch=dev
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  GITHUB_COMMIT_SHA: ${{ github.event.pull_request.base.sha}}
            - name: commit changes
              uses: stefanzweifel/git-auto-commit-action@v5
              with:
                  commit_message: "genai: /docs [skip ci]"
                  branch: ${{ github.head_ref || github.ref_name }}
                  file_pattern: packages/**/*.ts
            - name: Archive genai results
              if: always()
              uses: actions/upload-artifact@v4
              with:
                  name: genai-results
                  path: ./temp/genai/**
