name: genai pull request commit review
on:
    pull_request:
        paths:
            - yarn.lock
            - ".github/workflows/ollama.yml"
            - "packages/core/**/*"
            - "packages/cli/**/*"
            - "packages/samples/**/*"
jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            pull-requests: write
            models: read
        steps:
            - uses: actions/checkout@v4
              with:
                  submodules: "recursive"
                  fetch-depth: 10
            - uses: pnpm/action-setup@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: "22"
                  cache: pnpm
            - run: pnpm install --frozen-lockfile
            - name: compile
              run: pnpm build:cli
            - name: git stuff
              run: git fetch origin && git pull origin dev:dev
            - name: genaiscript pr-review-commit
              run: node packages/cli/dist/src/index.js run pr-review-commit -p github --out ./temp/genai/pr-review-commit -prr --out-trace $GITHUB_STEP_SUMMARY --vars defaultBranch=dev
              continue-on-error: true
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  GITHUB_COMMIT_SHA: ${{ github.event.pull_request.head.sha}}
