name: genai investigator
on:
    workflow_run:
        workflows: ["build", "playwright", "ollama"]
        types:
            - completed
concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event.workflow_run.event }}-${{ github.event.workflow_run.conclusion }}
    cancel-in-progress: true
permissions:
    contents: read
    actions: read
    pull-requests: write
    models: read
jobs:
    investigate:
        # Only run this job if the workflow run concluded with a failure
        # and was triggered by a pull request event
        if: ${{ github.event.workflow_run.conclusion == 'failure' && github.event.workflow_run.event == 'pull_request' }}
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  submodules: "recursive"
                  fetch-depth: 10
            - uses: pnpm/action-setup@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: "22"
                  cache: pnpm
            - run: pnpm install --frozen-lockfile
            - name: compile
              run: pnpm compile
            - name: genaiscript gai
              run: node packages/cli/dist/src/index.js run gai -p github --pull-request-comment --vars "runId=${{ github.event.workflow_run.id }}" --out-trace $GITHUB_STEP_SUMMARY
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
