name: google tests
permissions:
    contents: read
on:
    workflow_dispatch:
    release:
        types:
            - published
    pull_request:
        paths:
            - yarn.lock
            - ".github/workflows/google.yml"
            - "packages/core/**/*"
            - "packages/cli/**/*"
            - "packages/samples/**/*"
concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}-google
    cancel-in-progress: true
jobs:
    tests:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  submodules: "recursive"
                  fetch-depth: 0
            - uses: pnpm/action-setup@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: "22"
                  cache: pnpm
            - run: pnpm install --frozen-lockfile
            - name: compile
              run: pnpm build:cli
            - name: poem
              run: pnpm run:script poem -p google --out-trace $GITHUB_STEP_SUMMARY
              env:
                  GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
