name: npx pr poem
on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  generate-poem:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
      models: read
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: Generate poem
        run: npx --yes genaiscript run npx-poem -prd
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}