name: npx pr poem
on:
    workflow_dispatch:
    pull_request:
        types: [opened, synchronize, reopened]
permissions:
    pull-requests: write
    contents: read
    models: read
jobs:
    generate-poem:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: "20"
                  cache: "yarn"
            - name: Generate poem
              run: npx --yes genaiscript run poem -prd
              working-directory: ./packages/sample
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
